AppBundle\Entity\Post:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: text
        summary:
            type: text
        content:
            type: text
        authorEmail:
            type: text
        publishedAt:
            type: datetime
    lifecycleCallbacks: {  }
